name: Deploy

on:
  push:
    branches:
      - main

  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up ssh key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_ssh_key.pem
        chmod 600 ~/.ssh/ec2_ssh_key.pem
      
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_ssh_key.pem ubuntu@${{ secrets.PUBLIC_IP }} << EOF
        cd /home/ubuntu/hngx-stage2-fastapi-book-project
        git pull origin main
        source venv/bin/activate
        pip install -r requirements.txt
        sudo systemctl restart hngx-stage2-fastapi-book-project
        EOF